"""Centralized language packs and language normalization.

Two surfaces use language packs:

- ``EVIDENCE_PACKS`` — used by ``audit_site.build_html_report`` for the
  evidence/coverage report that the audit script writes directly.
- ``REPORT_PACKS`` — used by ``render_report_html.build_html`` for the
  final scored report.

Keep them separate dicts because they cover non-overlapping keys, but
both live here so adding a new language is a single-file change.
"""
from __future__ import annotations

EVIDENCE_PACKS: dict[str, dict[str, str]] = {
    "en": {
        "html_lang": "en",
        "title_prefix": "SEO/GEO Audit Report",
        "heading": "SEO/GEO Audit Report",
        "lede": "Report view for <strong>{target_url}</strong>. This page captures crawl coverage, structural signals, and any collected performance averages. Final scored conclusions should still be written using the scoring rubric and report template.",
        "snapshot": "Snapshot",
        "mode": "Mode",
        "output_style": "Output style",
        "crawl_cap": "Crawl cap",
        "pages_sampled": "Pages sampled",
        "performance_urls": "Performance URLs",
        "performance_errors": "Performance errors",
        "coverage_rates": "Coverage Rates",
        "signal": "Signal",
        "coverage_percent": "Coverage %",
        "template_mix": "Template Mix",
        "template": "Template",
        "pages": "Pages",
        "key_site_signals": "Key Site Signals",
        "llms_txt_present": "llms.txt present",
        "llms_txt_url": "llms.txt URL",
        "robots_sitemaps": "Robots discovered sitemaps",
        "processed_sitemaps": "Processed sitemaps",
        "security_headers": "Security Headers",
        "header": "Header",
        "status": "Status",
        "present": "present",
        "missing": "missing",
        "recurring_crawl_issues": "Recurring Crawl Issues",
        "issue": "Issue",
        "occurrences": "Occurrences",
        "performance_coverage": "Performance Coverage",
        "provider": "Provider",
        "representative_urls": "Representative URLs",
        "tested_urls": "Tested URLs",
        "category": "Category",
        "average_score": "Average score",
        "sampled_pages": "Sampled Pages",
        "url": "URL",
        "discovery_source": "Discovery source",
        "title": "Title",
        "raw_words": "Raw words",
        "rendered_words": "Rendered words",
        "no_pages_sampled": "No pages sampled.",
        "no_performance_data": "No {strategy} performance data collected.",
        "reading_this_report": "Reading this report:",
        "reading_this_report_body": "treat it as a structured evidence report, not the final scorecard by itself. Use the crawl and performance evidence here together with the scoring rubric to produce the final 0-100 section scores and roadmap.",
        "yes": "Yes",
        "no": "No",
        "none": "None",
        "no_data": "No data available.",
    },
    "zh": {
        "html_lang": "zh",
        "title_prefix": "SEO/GEO 审核报告",
        "heading": "SEO/GEO 审核报告",
        "lede": "<strong>{target_url}</strong> 的报告视图。本页面汇总抓取覆盖、结构信号以及已收集的性能均值。最终评分结论仍应结合评分规则与报告模板来撰写。",
        "snapshot": "概览",
        "mode": "模式",
        "output_style": "输出风格",
        "crawl_cap": "抓取上限",
        "pages_sampled": "已采样页面",
        "performance_urls": "性能测试 URL 数",
        "performance_errors": "性能错误数",
        "coverage_rates": "覆盖率",
        "signal": "信号",
        "coverage_percent": "覆盖率 %",
        "template_mix": "模板分布",
        "template": "模板",
        "pages": "页面数",
        "key_site_signals": "关键站点信号",
        "llms_txt_present": "是否存在 llms.txt",
        "llms_txt_url": "llms.txt URL",
        "robots_sitemaps": "robots.txt 发现的站点地图",
        "processed_sitemaps": "已处理站点地图",
        "security_headers": "安全响应头",
        "header": "Header",
        "status": "状态",
        "present": "存在",
        "missing": "缺失",
        "recurring_crawl_issues": "重复出现的抓取问题",
        "issue": "问题",
        "occurrences": "出现次数",
        "performance_coverage": "性能覆盖",
        "provider": "来源",
        "representative_urls": "代表性 URL",
        "tested_urls": "测试 URL",
        "category": "类别",
        "average_score": "平均得分",
        "sampled_pages": "采样页面",
        "url": "URL",
        "discovery_source": "发现来源",
        "title": "标题",
        "raw_words": "Raw 字数",
        "rendered_words": "渲染后字数",
        "no_pages_sampled": "没有采样页面。",
        "no_performance_data": "未收集 {strategy} 性能数据。",
        "reading_this_report": "阅读说明：",
        "reading_this_report_body": "请将其视为结构化证据报告，而不是最终评分卡本身。请结合抓取与性能证据以及评分规则，产出最终 0-100 分分项评分与实施路线图。",
        "yes": "是",
        "no": "否",
        "none": "无",
        "no_data": "暂无数据。",
    },
}

REPORT_PACKS: dict[str, dict[str, str]] = {
    "en": {
        "nav_top": "Back to Top",
        "nav_snapshot": "Snapshot",
        "nav_scorecard": "Scorecard",
        "nav_sections": "Findings",
        "nav_performance": "Performance",
        "nav_roadmap": "Roadmap",
        "nav_method": "Notes",
        "report_for": "SEO + GEO Report for",
        "overall_score": "Overall Score",
        "powered_by": "Powered by SEO GEO Skills",
        "powered_by_prefix": "Powered by",
        "report_generated_by": "Report generated by",
        "top_wins": "Top Wins",
        "top_issues": "Top Issues",
        "scorecard": "Scorecard",
        "weighted_total": "Weighted Total",
        "section_findings": "Section Findings",
        "passed_items": "Passed items",
        "issues": "Issues",
        "recommended_actions": "Recommended actions",
        "pagespeed_conclusion": "PageSpeed Conclusion",
        "mobile": "Mobile",
        "desktop": "Desktop",
        "average_performance": "Average performance",
        "pattern": "Pattern",
        "largest_issues": "Largest issues",
        "prioritized_roadmap": "Prioritized Roadmap",
        "method_notes": "Notes",
        "generated_artifacts": "Artifacts",
        "section": "Section",
        "score": "Score",
        "weight": "Weight",
        "weighted": "Contribution",
        "notes": "Notes",
        "generated_at": "Generated",
        "not_provided": "Not provided",
    },
    "zh": {
        "nav_top": "回到顶部",
        "nav_snapshot": "概览",
        "nav_scorecard": "评分表",
        "nav_sections": "分项发现",
        "nav_performance": "性能",
        "nav_roadmap": "路线图",
        "nav_method": "备注",
        "report_for": "SEO + GEO 报告：",
        "overall_score": "总分",
        "powered_by": "由 SEO GEO Skills 提供支持",
        "powered_by_prefix": "由",
        "report_generated_by": "报告由",
        "top_wins": "主要亮点",
        "top_issues": "主要问题",
        "scorecard": "评分表",
        "weighted_total": "加权总分",
        "section_findings": "分项发现",
        "passed_items": "通过项",
        "issues": "问题",
        "recommended_actions": "建议动作",
        "pagespeed_conclusion": "PageSpeed 结论",
        "mobile": "移动端",
        "desktop": "桌面端",
        "average_performance": "平均性能",
        "pattern": "模式",
        "largest_issues": "最大问题",
        "prioritized_roadmap": "优先路线图",
        "method_notes": "备注",
        "generated_artifacts": "产物",
        "section": "分项",
        "score": "得分",
        "weight": "权重",
        "weighted": "贡献",
        "notes": "说明",
        "generated_at": "生成时间",
        "not_provided": "未提供",
    },
}


def normalize_report_language(value: str | None) -> str:
    """Normalize a user-supplied language token into the canonical pack key."""
    raw = (value or "english").strip().lower()
    if raw in {"zh", "zh-cn", "zh-tw", "chinese", "中文", "简体中文", "繁體中文", "traditional chinese", "simplified chinese"}:
        return "zh"
    return "en"
