#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse


LANGUAGE_PACKS = {
    "en": {
        "nav_top": "Top",
        "nav_snapshot": "Snapshot",
        "nav_scorecard": "Scorecard",
        "nav_sections": "Findings",
        "nav_performance": "Performance",
        "nav_roadmap": "Roadmap",
        "nav_method": "Notes",
        "report_for": "SEO + GEO Report for",
        "overall_score": "Overall Score",
        "powered_by": "Powered by SEO GEO Skills",
        "report_generated_by": "Report generated by",
        "top_wins": "Top Wins",
        "top_issues": "Top Issues",
        "scorecard": "Scorecard",
        "weighted_total": "Weighted Total",
        "section_findings": "Section Findings",
        "passed_items": "Passed items",
        "issues": "Issues",
        "recommended_actions": "Recommended actions",
        "pagespeed_conclusion": "PageSpeed Conclusion",
        "mobile": "Mobile",
        "desktop": "Desktop",
        "average_performance": "Average performance",
        "pattern": "Pattern",
        "largest_issues": "Largest issues",
        "prioritized_roadmap": "Prioritized Roadmap",
        "method_notes": "Notes",
        "generated_artifacts": "Artifacts",
        "section": "Section",
        "score": "Section Score (0-100)",
        "weight": "Weight (%)",
        "weighted": "Contribution",
        "notes": "Notes",
        "generated_at": "Generated",
        "not_provided": "Not provided",
    },
    "zh": {
        "nav_top": "顶部",
        "nav_snapshot": "概览",
        "nav_scorecard": "评分表",
        "nav_sections": "分项发现",
        "nav_performance": "性能",
        "nav_roadmap": "路线图",
        "nav_method": "备注",
        "report_for": "SEO + GEO 报告：",
        "overall_score": "总分",
        "powered_by": "由 SEO GEO Skills 提供支持",
        "report_generated_by": "报告由",
        "top_wins": "主要亮点",
        "top_issues": "主要问题",
        "scorecard": "评分表",
        "weighted_total": "加权总分",
        "section_findings": "分项发现",
        "passed_items": "通过项",
        "issues": "问题",
        "recommended_actions": "建议动作",
        "pagespeed_conclusion": "PageSpeed 结论",
        "mobile": "移动端",
        "desktop": "桌面端",
        "average_performance": "平均性能",
        "pattern": "模式",
        "largest_issues": "最大问题",
        "prioritized_roadmap": "优先路线图",
        "method_notes": "备注",
        "generated_artifacts": "产物",
        "section": "分项",
        "score": "板块得分（100分制）",
        "weight": "权重（%）",
        "weighted": "对总分贡献",
        "notes": "说明",
        "generated_at": "生成时间",
        "not_provided": "未提供",
    },
}


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_language(value: str | None) -> str:
    raw = (value or "english").strip().lower()
    if raw in {"zh", "zh-cn", "zh-tw", "chinese", "中文", "简体中文", "繁體中文"}:
        return "zh"
    return "en"


def slugify(value: str) -> str:
    value = re.sub(r"<[^>]+>", "", value)
    value = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", "-", value.strip().lower())
    return value.strip("-") or "section"


def severity_class(value: str) -> str:
    return {
        "P0": "sev-p0",
        "P1": "sev-p1",
        "P2": "sev-p2",
        "P3": "sev-p3",
    }.get((value or "").upper(), "sev-generic")


def render_list(items: list[str], empty_label: str) -> str:
    if not items:
        return f"<p class='empty'>{html.escape(empty_label)}</p>"
    return "<ul>" + "".join(f"<li>{html.escape(item)}</li>" for item in items) + "</ul>"


def render_issue_items(items: list[object], empty_label: str) -> str:
    if not items:
        return f"<p class='empty'>{html.escape(empty_label)}</p>"
    rendered = []
    for item in items:
        if isinstance(item, dict):
            severity = str(item.get("severity", "")).upper()
            title = str(item.get("title", "")).strip()
            detail = str(item.get("detail", "")).strip()
            if severity or title or detail:
                badge = f"<span class='severity {severity_class(severity)}'>{html.escape(severity or 'Issue')}</span>"
                headline = html.escape(title or detail or severity or "Issue")
                body = f"<p>{html.escape(detail)}</p>" if detail and detail != title else ""
                rendered.append(f"<li class='issue-item'>{badge}<div><strong>{headline}</strong>{body}</div></li>")
            continue
        rendered.append(f"<li>{html.escape(str(item))}</li>")
    return "<ul class='issues-list'>" + "".join(rendered) + "</ul>"


def render_snapshot(snapshot: list[dict], empty_label: str) -> str:
    if not snapshot:
        return f"<p class='empty'>{html.escape(empty_label)}</p>"
    cards = []
    for item in snapshot:
        label = html.escape(str(item.get("label", "")))
        value = html.escape(str(item.get("value", "")))
        cards.append(
            "<article class='snapshot-card'>"
            f"<div class='snapshot-label'>{label}</div>"
            f"<div class='snapshot-value'>{value}</div>"
            "</article>"
        )
    return "<div class='snapshot-grid'>" + "".join(cards) + "</div>"


def snapshot_label_key(label: str) -> str:
    normalized = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "", label.strip().lower())
    mapping = {
        "target": "target",
        "目标": "target",
        "mode": "mode",
        "模式": "mode",
        "pagessampled": "pages_sampled",
        "已采样页面": "pages_sampled",
        "performanceevidence": "performance_evidence",
        "性能证据": "performance_evidence",
        "outputstyle": "output_style",
        "输出风格": "output_style",
        "confidence": "confidence",
        "置信度": "confidence",
    }
    return mapping.get(normalized, normalized)


def prepare_snapshot(snapshot: list[dict]) -> list[dict]:
    by_key: dict[str, dict] = {}
    ordered_unknown: list[dict] = []
    for item in snapshot:
        key = snapshot_label_key(str(item.get("label", "")))
        if key in {"output_style", "confidence"}:
            continue
        if key in {"target", "mode", "pages_sampled", "performance_evidence"}:
            by_key[key] = item
        else:
            ordered_unknown.append(item)
    ordered = []
    for key in ("target", "mode", "pages_sampled", "performance_evidence"):
        if key in by_key:
            ordered.append(by_key[key])
    ordered.extend(ordered_unknown)
    return ordered


def parse_number(value: object) -> float | None:
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        cleaned = value.strip().rstrip("%").strip()
        try:
            return float(cleaned)
        except ValueError:
            return None
    return None


def format_weight(value: object) -> str:
    if isinstance(value, str) and value.strip().endswith("%"):
        return value.strip()
    parsed = parse_number(value)
    if parsed is None:
        return str(value or "")
    return f"{parsed:g}%"


def compute_weighted_value(row: dict) -> float | None:
    weighted = parse_number(row.get("weighted_score", row.get("weighted")))
    if weighted is not None:
        return weighted
    score = parse_number(row.get("score"))
    weight = parse_number(row.get("weight"))
    if score is not None and weight is not None:
        return score * weight / 100.0
    return None


def compute_weighted_total(rows: list[dict]) -> float | None:
    total = 0.0
    found = False
    for row in rows:
        weighted = compute_weighted_value(row)
        if weighted is not None:
            total += weighted
            found = True
    return round(total, 2) if found else None


def format_generated_at(value: str, language: str) -> str:
    raw = (value or "").strip()
    if not raw:
        return raw
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return raw
    if language == "zh":
        return parsed.strftime("%Y-%m-%d %H:%M")
    return parsed.strftime("%b %d, %Y %H:%M")


def render_score_table(rows: list[dict], ui: dict[str, str], empty_label: str) -> str:
    if not rows:
        return f"<p class='empty'>{html.escape(empty_label)}</p>"
    body_rows = []
    for row in rows:
        weighted_value = compute_weighted_value(row)
        body_rows.append(
            "<tr>"
            f"<td>{html.escape(str(row.get('section', '')))}</td>"
            f"<td>{html.escape(str(row.get('score', '')))}</td>"
            f"<td>{html.escape(format_weight(row.get('weight', '')))}</td>"
            f"<td>{html.escape(f'{weighted_value:g}' if weighted_value is not None else '')}</td>"
            f"<td>{html.escape(str(row.get('notes', row.get('note', ''))))}</td>"
            "</tr>"
        )
    weighted_total = compute_weighted_total(rows)
    summary_markup = ""
    if weighted_total is not None:
        summary_markup = (
            "<div class='score-total'>"
            f"<span>{html.escape(ui['weighted_total'])}</span>"
            f"<strong>{html.escape(f'{weighted_total:g} / 100')}</strong>"
            "</div>"
        )
    return (
        "<div class='scorecard-wrap'>"
        "<table class='score-table'>"
        "<thead><tr>"
        f"<th>{html.escape(ui['section'])}</th>"
        f"<th>{html.escape(ui['score'])}</th>"
        f"<th>{html.escape(ui['weight'])}</th>"
        f"<th>{html.escape(ui['weighted'])}</th>"
        f"<th>{html.escape(ui['notes'])}</th>"
        "</tr></thead>"
        f"<tbody>{''.join(body_rows)}</tbody></table>"
        f"{summary_markup}</div>"
    )


def render_performance_column(block: dict, heading: str, ui: dict[str, str], empty_label: str) -> str:
    if not block:
        return (
            "<article class='metric-card panel'>"
            f"<h3>{html.escape(heading)}</h3>"
            f"<p class='empty'>{html.escape(empty_label)}</p>"
            "</article>"
        )
    largest_issues = block.get("largest_issues", [])
    return (
        "<article class='metric-card panel'>"
        f"<h3>{html.escape(heading)}</h3>"
        "<dl class='metric-list'>"
        f"<div><dt>{html.escape(ui['average_performance'])}</dt><dd>{html.escape(str(block.get('average_performance', '')))}</dd></div>"
        f"<div><dt>{html.escape(ui['pattern'])}</dt><dd>{html.escape(str(block.get('pattern', '')))}</dd></div>"
        "</dl>"
        f"<div class='metric-subtitle'>{html.escape(ui['largest_issues'])}</div>"
        f"{render_list([str(item) for item in largest_issues], empty_label)}"
        "</article>"
    )


def build_html(payload: dict) -> str:
    language = normalize_language(payload.get("language"))
    ui = {**LANGUAGE_PACKS[language], **payload.get("ui_text", {})}

    title = str(payload.get("title", "SEO + GEO Audit Report"))
    display_title = str(payload.get("display_title", title))
    target_url = str(payload.get("target_url", ""))
    repo_url = str(payload.get("repo_url", "")).strip()
    repo_label = str(payload.get("repo_label", "SEO GEO Skills")).strip()
    generated_at = str(payload.get("generated_at", datetime.now(timezone.utc).replace(microsecond=0).isoformat()))
    snapshot = prepare_snapshot(payload.get("snapshot", []))
    section_scores = payload.get("section_scores", [])
    top_wins = [str(item) for item in payload.get("top_wins", [])]
    top_issues = [str(item) for item in payload.get("top_issues", [])]
    sections = payload.get("sections", [])
    pagespeed = payload.get("pagespeed_conclusion", {})
    roadmap = payload.get("roadmap", {})
    method_notes = [str(item) for item in payload.get("method_notes", [])]
    report_subject = str(payload.get("report_subject", "")).strip()
    if not report_subject:
        parsed = urlparse(target_url)
        report_subject = parsed.netloc or parsed.path or str(payload.get("target_domain", "")).strip()
    display_generated_at = format_generated_at(generated_at, language)
    report_heading = f"{ui['report_for']} {report_subject}".strip() if report_subject else display_title
    rendered_sections = []
    for section in sections:
        section_title = str(section.get("title", "Section"))
        section_id = slugify(section_title)
        rendered_sections.append(
            "<section class='finding-section panel' id='{id}'>"
            "<div class='section-heading'>"
            "<div>"
            f"<div class='section-kicker'>{html.escape(ui['section_findings'])}</div>"
            f"<h2>{html.escape(section_title)}</h2>"
            "</div>"
            f"<div class='score-pill'>{html.escape(str(section.get('score', '')))}</div>"
            "</div>"
            "<div class='finding-grid'>"
            "<article class='finding-block'>"
            f"<h3>{html.escape(ui['passed_items'])}</h3>"
            f"{render_list([str(item) for item in section.get('passed_items', [])], ui['not_provided'])}"
            "</article>"
            "<article class='finding-block'>"
            f"<h3>{html.escape(ui['issues'])}</h3>"
            f"{render_issue_items(section.get('issues', []), ui['not_provided'])}"
            "</article>"
            "<article class='finding-block'>"
            f"<h3>{html.escape(ui['recommended_actions'])}</h3>"
            f"{render_list([str(item) for item in section.get('recommended_actions', [])], ui['not_provided'])}"
            "</article>"
            "</div>"
            "</section>"
        .format(id=section_id))

    return f"""<!doctype html>
<html lang="{html.escape(language)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)} - {html.escape(target_url)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Noto+Sans:wght@400;500;700&display=swap" rel="stylesheet">
  <style>
    :root {{
      color-scheme: light;
      --bg: #ffffff;
      --ink: #1c1c1e;
      --muted: #555a6a;
      --line: rgb(224,226,232);
      --blue: #5b76fe;
      --blue-pressed: #2a41b6;
      --panel: #ffffff;
      --coral: #ffc6c6;
      --rose: #ffd8f4;
      --teal: #c3faf5;
      --orange: #ffe6cd;
      --green: #d9f5e8;
      --yellow: #fff1bf;
      --radius-sm: 8px;
      --radius-md: 12px;
      --radius-lg: 24px;
      --shadow: rgb(224,226,232) 0px 0px 0px 1px;
      --font-display: 'Inter', ui-sans-serif, system-ui, sans-serif;
      --font-body: 'Noto Sans', 'Inter', sans-serif;
    }}
    * {{ box-sizing: border-box; }}
    html {{ scroll-behavior: smooth; }}
    body {{
      margin: 0;
      background:
        radial-gradient(circle at top left, rgba(255, 216, 244, 0.55), transparent 28%),
        radial-gradient(circle at top right, rgba(195, 250, 245, 0.45), transparent 28%),
        linear-gradient(180deg, #ffffff 0%, #fbfbfd 100%);
      color: var(--ink);
      font-family: var(--font-body);
      line-height: 1.55;
      -webkit-font-smoothing: antialiased;
    }}
    a {{ color: var(--blue); text-decoration: none; }}
    main {{ max-width: 1240px; margin: 0 auto; padding: 20px 20px 80px; }}
    .topbar {{
      position: sticky;
      top: 0;
      z-index: 40;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      padding: 12px 20px;
      background: rgba(255,255,255,0.84);
      backdrop-filter: blur(10px);
      box-shadow: var(--shadow);
    }}
    .toplink {{
      color: var(--ink);
      font-family: var(--font-display);
      font-size: 13px;
      font-weight: 700;
      letter-spacing: 0.02em;
    }}
    .nav {{
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
      justify-content: flex-end;
    }}
    .nav a {{
      color: var(--muted);
      padding: 8px 12px;
      border-radius: 999px;
      background: rgba(91,118,254,0.06);
      box-shadow: inset 0 0 0 1px rgba(91,118,254,0.08);
      font-size: 12px;
      transition: background 120ms ease, color 120ms ease;
    }}
    .nav a:hover {{
      background: rgba(91,118,254,0.12);
      color: var(--blue-pressed);
    }}
    .hero {{
      padding: 48px 0 28px;
      display: block;
    }}
    h1 {{
      margin: 0 0 16px;
      font-family: var(--font-display);
      font-size: clamp(2rem, 5vw, 3.25rem);
      line-height: 1.02;
      letter-spacing: -0.05em;
      font-weight: 800;
      max-width: 20ch;
    }}
    .report-prefix {{
      color: var(--ink);
    }}
    .report-domain {{
      color: var(--blue-pressed);
    }}
    .hero-links {{
      display: contents;
    }}
    .hero-meta {{
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      margin-top: 4px;
      font-size: 13px;
      color: var(--muted);
    }}
    .meta-chip {{
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 10px 14px;
      border-radius: 999px;
      background: rgba(255,255,255,0.72);
      box-shadow: var(--shadow);
      color: var(--muted);
    }}
    .meta-chip a {{
      color: var(--blue-pressed);
      font-weight: 600;
    }}
    .panel {{
      background: var(--panel);
      border-radius: var(--radius-lg);
      box-shadow: var(--shadow);
      padding: 24px;
    }}
    .section-block {{ margin-top: 22px; }}
    .section-block h2 {{
      font-family: var(--font-display);
      font-size: 38px;
      line-height: 1.04;
      letter-spacing: -0.05em;
      margin: 0 0 16px;
    }}
    .snapshot-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 12px;
    }}
    .snapshot-card {{
      padding: 16px;
      border-radius: var(--radius-md);
      background: #fff;
      box-shadow: var(--shadow);
    }}
    .snapshot-label {{
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--muted);
      margin-bottom: 8px;
    }}
    .snapshot-value {{
      font-family: var(--font-display);
      font-size: 20px;
      line-height: 1.2;
      font-weight: 700;
      letter-spacing: -0.03em;
    }}
    .highlight-grid {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 18px;
      margin-top: 18px;
    }}
    .highlight-card h3,
    .metric-card h3,
    .finding-block h3 {{
      margin: 0 0 12px;
      font-family: var(--font-display);
      font-size: 22px;
      letter-spacing: -0.03em;
    }}
    .highlight-card.wins {{ background: var(--teal); }}
    .highlight-card.issues {{ background: var(--coral); }}
    .score-table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 14px;
    }}
    .score-table th,
    .score-table td {{
      text-align: left;
      padding: 12px 10px;
      border-bottom: 1px solid var(--line);
      vertical-align: top;
    }}
    .score-table thead th {{ color: var(--muted); font-weight: 600; }}
    .scorecard-wrap {{
      display: grid;
      gap: 18px;
    }}
    .score-total {{
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      padding: 16px 18px;
      border-radius: var(--radius-md);
      background: rgba(91,118,254,0.08);
    }}
    .score-total span {{
      color: var(--muted);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }}
    .score-total strong {{
      font-family: var(--font-display);
      font-size: 28px;
      line-height: 1;
      letter-spacing: -0.04em;
    }}
    .finding-section {{ margin-top: 18px; }}
    .section-heading {{
      display: flex;
      align-items: start;
      justify-content: space-between;
      gap: 16px;
      margin-bottom: 18px;
    }}
    .section-kicker {{
      color: var(--muted);
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      margin-bottom: 6px;
    }}
    .section-heading h2 {{
      margin: 0;
      font-family: var(--font-display);
      font-size: 30px;
      line-height: 1.05;
      letter-spacing: -0.04em;
    }}
    .score-pill {{
      padding: 10px 16px;
      border-radius: 999px;
      background: var(--yellow);
      font-family: var(--font-display);
      font-size: 18px;
      font-weight: 800;
      min-width: 64px;
      text-align: center;
    }}
    .finding-grid {{
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 14px;
    }}
    .finding-block {{
      padding: 18px;
      border-radius: var(--radius-md);
      background: rgba(255,255,255,0.9);
      box-shadow: var(--shadow);
    }}
    ul {{ margin: 0; padding-left: 18px; }}
    li + li {{ margin-top: 8px; }}
    .issues-list {{
      list-style: none;
      padding: 0;
      display: grid;
      gap: 12px;
    }}
    .issue-item {{
      display: grid;
      grid-template-columns: auto 1fr;
      gap: 10px;
      align-items: start;
    }}
    .severity {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: 42px;
      padding: 6px 10px;
      border-radius: 999px;
      font-family: var(--font-display);
      font-size: 11px;
      font-weight: 800;
      letter-spacing: 0.06em;
      text-transform: uppercase;
    }}
    .sev-p0 {{ background: #600000; color: #fff; }}
    .sev-p1 {{ background: #ffd8f4; color: #5a2555; }}
    .sev-p2 {{ background: #ffe6cd; color: #7d4d00; }}
    .sev-p3 {{ background: #d9f5e8; color: #0d6540; }}
    .sev-generic {{ background: #eef0f6; color: #3b4252; }}
    .issue-item p {{
      margin: 6px 0 0;
      color: var(--muted);
      font-size: 14px;
    }}
    .metric-grid {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 18px;
    }}
    .metric-card {{
      background: linear-gradient(180deg, rgba(253,224,240,0.42), rgba(255,255,255,0.92));
    }}
    .metric-list {{
      display: grid;
      gap: 10px;
      margin: 0 0 14px;
    }}
    .metric-list div {{
      display: grid;
      gap: 4px;
    }}
    .metric-list dt {{
      color: var(--muted);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }}
    .metric-list dd {{
      margin: 0;
      font-family: var(--font-display);
      font-size: 18px;
      font-weight: 700;
      letter-spacing: -0.03em;
    }}
    .metric-subtitle {{
      margin-bottom: 8px;
      color: var(--muted);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }}
    .roadmap-grid {{
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 14px;
    }}
    .roadmap-column {{
      padding: 18px;
      border-radius: var(--radius-md);
      box-shadow: var(--shadow);
      background: rgba(255,255,255,0.95);
    }}
    .roadmap-column h3 {{
      margin: 0 0 12px;
      font-family: var(--font-display);
      font-size: 24px;
    }}
    .roadmap-p0 {{ background: var(--coral); }}
    .roadmap-p1 {{ background: var(--rose); }}
    .roadmap-p2 {{ background: var(--orange); }}
    .roadmap-p3 {{ background: var(--green); }}
    .empty {{
      color: var(--muted);
      font-style: italic;
      margin: 0;
    }}
    footer {{
      margin-top: 28px;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      flex-wrap: wrap;
      color: var(--muted);
      font-size: 12px;
    }}
    footer a {{
      color: var(--blue-pressed);
      font-weight: 600;
    }}
    @media (max-width: 960px) {{
      .highlight-grid,
      .metric-grid,
      .roadmap-grid,
      .finding-grid {{
        grid-template-columns: 1fr;
      }}
      .topbar {{
        align-items: flex-start;
        flex-direction: column;
      }}
    }}
  </style>
</head>
<body>
  <div class="topbar">
    <a class="toplink" href="#top">{html.escape(ui['nav_top'])}</a>
    <nav class="nav">
      <a href="#snapshot">{html.escape(ui['nav_snapshot'])}</a>
      <a href="#scorecard">{html.escape(ui['nav_scorecard'])}</a>
      <a href="#sections">{html.escape(ui['nav_sections'])}</a>
      <a href="#performance">{html.escape(ui['nav_performance'])}</a>
      <a href="#roadmap">{html.escape(ui['nav_roadmap'])}</a>
      <a href="#method">{html.escape(ui['nav_method'])}</a>
    </nav>
  </div>
  <main>
    <section class="hero" id="top">
      <div>
        <h1><span class="report-prefix">{html.escape(ui['report_for'])}</span> <span class="report-domain">{html.escape(report_subject or display_title)}</span></h1>
        <div class="hero-meta">
          <span class="meta-chip">{html.escape(ui['generated_at'])}: {html.escape(display_generated_at)}</span>
          {f"<span class='meta-chip'><a href='{html.escape(repo_url)}'>{html.escape(repo_label)}</a></span>" if repo_url else ""}
        </div>
      </div>
    </section>

    <section class="section-block" id="snapshot">
      <h2>{html.escape(ui['nav_snapshot'])}</h2>
      {render_snapshot(snapshot, ui['not_provided'])}
    </section>

    <section class="section-block" id="scorecard">
      <article class="panel">
        <h2>{html.escape(ui['scorecard'])}</h2>
        {render_score_table(section_scores, ui, ui['not_provided'])}
      </article>
      <div class="highlight-grid">
        <article class="highlight-card wins panel">
          <h3>{html.escape(ui['top_wins'])}</h3>
          {render_list(top_wins, ui['not_provided'])}
        </article>
        <article class="highlight-card issues panel">
          <h3>{html.escape(ui['top_issues'])}</h3>
          {render_list(top_issues, ui['not_provided'])}
        </article>
      </div>
    </section>

    <section class="section-block" id="sections">
      <h2>{html.escape(ui['section_findings'])}</h2>
      {''.join(rendered_sections)}
    </section>

    <section class="section-block" id="performance">
      <h2>{html.escape(ui['pagespeed_conclusion'])}</h2>
      <div class="metric-grid">
        {render_performance_column(pagespeed.get('mobile', {}), ui['mobile'], ui, ui['not_provided'])}
        {render_performance_column(pagespeed.get('desktop', {}), ui['desktop'], ui, ui['not_provided'])}
      </div>
      {f"<div class='panel' style='margin-top:18px'>{render_list([str(pagespeed.get('note'))], ui['not_provided'])}</div>" if pagespeed.get('note') else ""}
    </section>

    <section class="section-block" id="roadmap">
      <h2>{html.escape(ui['prioritized_roadmap'])}</h2>
      <div class="roadmap-grid">
        <article class="roadmap-column roadmap-p0"><h3>P0</h3>{render_list([str(item) for item in roadmap.get('P0', [])], ui['not_provided'])}</article>
        <article class="roadmap-column roadmap-p1"><h3>P1</h3>{render_list([str(item) for item in roadmap.get('P1', [])], ui['not_provided'])}</article>
        <article class="roadmap-column roadmap-p2"><h3>P2</h3>{render_list([str(item) for item in roadmap.get('P2', [])], ui['not_provided'])}</article>
        <article class="roadmap-column roadmap-p3"><h3>P3</h3>{render_list([str(item) for item in roadmap.get('P3', [])], ui['not_provided'])}</article>
      </div>
    </section>

    <section class="section-block" id="method">
      <article class="panel">
        <h2>{html.escape(ui['method_notes'])}</h2>
        {render_list(method_notes, ui['not_provided'])}
      </article>
    </section>

    <footer>
      {f"{html.escape(ui['report_generated_by'])} <a href='{html.escape(repo_url)}'>{html.escape(repo_label)}</a>" if repo_url else ""}
    </footer>
  </main>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Render a polished HTML report from a structured SEO/GEO report JSON payload.")
    parser.add_argument("--report-json", required=True, help="Path to the structured report JSON payload.")
    parser.add_argument("--out", required=True, help="Output HTML path.")
    args = parser.parse_args()

    payload = load_json(Path(args.report_json))
    html_payload = build_html(payload)
    Path(args.out).write_text(html_payload, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
